### ISSUE TITLE
Create issue-templates

### ISSUE THREAD

**Issue by TheoThmn** [remsfal/remsfal-backend#222]
**Description:**
To streamline and standardize the process of creating new issues in the "remsfal" project, I propose the creation of issue templates. These templates will guide contributors on providing necessary details for different types of issues (e.g., bug reports, feature requests, documentation updates).

**Tasks:**

- [ ] Identify common issue types (e.g., bug reports, feature requests, and documentation improvements).
- [ ] Create a markdown template for each type of issue.
- [ ] Add the templates to the .github/ISSUE_TEMPLATE/ directory.
- [ ] Test the templates to ensure they render correctly when creating a new issue.

**Acceptance Criteria:**

- Templates for bug reports, feature requests, and documentation updates are available.
- Templates are pre-populated with the required fields and guidelines.
- Templates are easy to use and improve the clarity of submitted issues.

This issue equally concerns [https://github.com/remsfal/remsfal-frontend](remsfal-frontend).

**Comment by astanik** [comment]
A very good example can be found here: https://github.com/keycloak/keycloak/tree/main/.github/ISSUE_TEMPLATE

The GitHub documentation about creating such templates can be found here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by astanik** [comment]
@TheoThmn Would you like to implement this issue?

**Comment by astanik** [comment]
This issue is related to https://github.com/remsfal/remsfal-frontend/issues/209

**Comment by TheoThmn** [comment]
> @TheoThmn Would you like to implement this issue?

Yes, please @astanik. I'd propose to implement the issue [222](https://github.com/remsfal/remsfal-frontend/issues/209) as well. That way the templates stay the same throughout the entire project.

**Comment by astanik** [comment]
Excellent! Can you please write a comment in issue https://github.com/remsfal/remsfal-frontend/issues/209 in order that i can assign you the task?

**Comment by TheoThmn** [comment]
I propose for this to be implemented in a new repository named ".github" in the remsfal-organization. That way, the templates will be set centrally for frontend and backend at the same time. 
[Further information on how to organization-wide community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#creating-a-repository-for-default-files)
What are your thoughts on this, @astanik?
